### ISSUE TITLE
cant run node PiCamera_accessory.js ? ideas?

### ISSUE THREAD

**Issue by raaffq** [Didel/HomeKitCam#10]
pi@raspberrypi:~/HomeKitCam $ ls
LICENSE  node_modules  package.json  PiCamera_accessory.js  README.md
pi@raspberrypi:~/HomeKitCam $ node PiCamera_accessory.js
/home/pi/HomeKitCam/PiCamera_accessory.js:25
    let sessionIdentifier = uuid.unparse(sessionID);
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
pi@raspberrypi:~/HomeKitCam $

**Comment by theopoon** [comment]
Please check your node version.

~/node -v

**Comment by raaffq** [comment]
pi@raspberrypi:~ $ node -v
v4.2.1

**Comment by theopoon** [comment]
Consider upgrading your node

**Comment by raaffq** [comment]
How I can update? I try pi@raspberrypi:~ $ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (10.2.1-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
pi@raspberrypi:~ $ node -b
node: bad option: -b
pi@raspberrypi:~ $ node -v
v4.2.1
pi@raspberrypi:~ $

**Comment by theopoon** [comment]
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by raaffq** [comment]
cant update , after update still showing old version
