### ISSUE TITLE
Will not start

### ISSUE THREAD

**Issue by darklordbrock** [Didel/HomeKitCam#5]
I cloned this down and ran npm install

when running `node PiCamera_accessory.js` I get the following output

/home/pi/HomeKitCam/PiCamera_accessory.js:25
    let sessionIdentifier = uuid.unparse(sessionID);
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by theopoon** [comment]
What is your node version?

**Comment by darklordbrock** [comment]
node -v
v4.2.1

**Comment by theopoon** [comment]
Well known issue of older node, please update your node to version 7

https://www.google.com.hk/search?q=SyntaxError%3A+Block-scoped+declarations+(let%2C+const%2C+function%2C+class)+not+yet+supported+outside+strict+mode
